[package]
name = "azur_lane_data_collector"
version = "2.0.0-beta.1"
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.winresource]
FileDescription = "Houston Tools Azur Lane Data Collector"

[lints]
workspace = true

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["derive"] }
humantime = "2.1.0"
image = { version = "0.25.4", default-features = false, features = ["webp"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"

azur_lane = { path = "../azur_lane" }
unity_read = { path = "../unity_read" }
utils = { path = "../utils" }

[dependencies.mlua]
version = "0.9.9"
features = ["lua54", "vendored"]

[build-dependencies]
utils_build = { path = "../utils_build" }
