[package]
name = "azur_lane_data_collector"
version = "1.7.2"
edition = "2021"
rust-version = "1.82"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.winres]
FileDescription = "Houston Tools Azur Lane Data Collector"

[lints]
workspace = true

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
image = { version = "0.25.3", default-features = false, features = ["webp"] }
once_cell = "1.20.2"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

azur_lane = { path = "../azur_lane" }
unity_read = { path = "../unity_read" }
utils = { path = "../utils" }

[dependencies.mlua]
version = "0.9.9"
# luajit is not supported because the game scripts have an absurd amount of constants
features = ["lua54", "vendored"]

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"
