brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_granularity = "Module"
match_block_trailing_comma = true
max_width = 100
wrap_comments = true
trailing_comma = "Vertical"
