[package]
name = "utils"
version = "5.0.0"
edition = "2021"
rust-version = "1.80"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
arrayvec = "0.7.6"
chrono = { version = "0.4.38", default-features = false, features = ["now"] }
smallvec = { version = "1.13.2", features = ["const_generics", "union"] }
thiserror = "1.0.64"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "fuzzy"
harness = false

[[bench]]
name = "str_as_data"
harness = false
